exports.INPUT_TYPE_NOT_SPECIFIED_FOR_THAT_COMMAND = 0;
exports.DAY_FOOD_DISH_CREATION_LIMIT = 1;
exports.FOOD_DISH_NAME_LESS_THAN_4_CHARS = 2;
exports.DAY_OF_MONTH_EQUAL_TO_0 = 3;
exports.WHOLE_DATE_IS_INVALID = 4;
